/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/policies': typeof PoliciesRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/policies': typeof PoliciesRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/policies': typeof PoliciesRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/dashboard'
    | '/evaluations'
    | '/policies'
    | '/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/dashboard'
    | '/evaluations'
    | '/policies'
    | '/telemetry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/dashboard'
    | '/evaluations'
    | '/policies'
    | '/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationsRoute: typeof EvaluationsRoute
  PoliciesRoute: typeof PoliciesRoute
  TelemetryRoute: typeof TelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EvaluationsRoute: EvaluationsRoute,
  PoliciesRoute: PoliciesRoute,
  TelemetryRoute: TelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
